#!/bin/sh

set -e

PREV_COMMIT=$1
POST_COMMIT=$2

echo 'post-checkout: Check diffs......'
DIFF=$(git diff $PREV_COMMIT..$POST_COMMIT --name-status --diff-filter=ADR | grep 'mkstarter')
if [[ $DIFF != "" ]]; then
    while read line
    do
        echo "$line"
    done <<END
    $DIFF
END
    echo 'File added/deleted in mkstarter. Re-run xcodegen'
    make -C "$(git rev-parse --show-toplevel)" run-xcodegen
fi
